serverAddr = "jp100.frp0.top"
serverPort = 2210
user ="PB9JEIlHBxmo"
loginFailExit = false
#上面是认证信息，不要修改
#下面的是一个完整连接的结构，其他协议请自行搜索frpc配置

[[proxies]]
type = "tcp"
#每个连接一个名称，不能修改
name="40s4yPcIwA2r"
localIP = "127.0.0.1"
#请填写需要远程访问的本地端口
localPort = 3389
#每个连接一个远程端口，访问地址 serverAddr:remotePort
remotePort = 30103
#启动报错时尝试删除下面两行
transport.useEncryption = true
transport.useCompression = true
