name: macOS VNC Server (Full Fixed)

on:
  workflow_dispatch:

jobs:
  macos-vnc:
    runs-on: macos-latest
    timeout-minutes: 360

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable VNC (Screen Sharing)
        run: |
          sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.screensharing.plist
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -users runner -access -on -privs -all

      - name: Generate VNC Password
        run: |
          VNC_PASS=$(openssl rand -hex 6)
          echo "VNC_PASSWORD=$VNC_PASS" >> $GITHUB_ENV

      - name: Set VNC Password
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -users runner -setvncpw -vncpw "${{ env.VNC_PASSWORD }}"
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent

      - name: Install & Start Tailscale (Fixed Service)
        run: |
          # 安装Tailscale
          brew install tailscale
          # 手动启动Tailscale服务（关键修复：brew安装后不自动启动）
          sudo nohup /opt/homebrew/opt/tailscale/bin/tailscaled > /tmp/tailscaled.log 2>&1 &
          # 等待服务启动（给3秒缓冲）
          sleep 3
          # 连接Tailscale（用auth key）
          sudo /opt/homebrew/bin/tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=macos-vnc-final-${GITHUB_RUN_ID}
          # 获取Tailscale IP
          echo "TAILSCALE_IP=$(sudo /opt/homebrew/bin/tailscale ip -4)" >> $GITHUB_ENV

      - name: Keep Alive & Show Info
        run: |
          echo "=== 最终访问信息 ==="
          echo "VNC地址: $TAILSCALE_IP:5900"
          echo "用户名: runner"
          echo "密码: $VNC_PASSWORD"
          echo "===================="
          
          while true; do
            echo "[$(date)] VNC + Tailscale 运行正常..."
            sleep 300
          done
