name: macOS VNC Server (TigerVNC Path Fixed)

on:
  workflow_dispatch:

jobs:
  macos-vnc:
    runs-on: macos-latest
    timeout-minutes: 3600

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install XQuartz and TigerVNC with Path Fix
        run: |
          # 安装X11服务器
          brew install --cask xquartz
          
          # 安装TigerVNC（正确包名）
          brew install tiger-vnc
          
          # 关键修复：确认VNC命令路径并添加到环境变量
          # Homebrew在macOS的默认安装路径（适配Intel和Apple Silicon）
          if [ -d "/usr/local/bin" ]; then
            export PATH="/usr/local/bin:$PATH"
          elif [ -d "/opt/homebrew/bin" ]; then
            export PATH="/opt/homebrew/bin:$PATH"
          fi
          # 验证VNC命令是否存在
          echo "VNC命令路径: $(which vncserver)"
          echo "VNC密码工具路径: $(which vncpasswd)"
          
          # 启动XQuartz并等待初始化
          open -a XQuartz
          sleep 5  # 延长等待时间，确保X11就绪

      - name: Configure VNC Server
        run: |
          # 再次确认环境变量（避免子shell路径丢失）
          if [ -d "/usr/local/bin" ]; then
            export PATH="/usr/local/bin:$PATH"
          elif [ -d "/opt/homebrew/bin" ]; then
            export PATH="/opt/homebrew/bin:$PATH"
          fi
          export LC_ALL=C
          export DISPLAY=:0
          
          # 生成随机密码
          VNC_PASS=$(openssl rand -hex 8)
          echo "VNC_PASSWORD=$VNC_PASS" >> "$GITHUB_ENV"
          
          # 配置VNC目录和密码（显式使用vncpasswd路径）
          mkdir -p ~/.vnc
          echo "$VNC_PASS" | $(which vncpasswd) -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          
          # 配置启动脚本
          cat > ~/.vnc/xstartup << 'EOF'
          #!/bin/bash
          export DISPLAY=:0
          openbox &
          xterm -ls -geometry 80x24+10+10 &
          EOF
          chmod +x ~/.vnc/xstartup
          
          # 启动VNC服务器（显式使用vncserver路径）
          $(which vncserver) -kill :0 || true
          $(which vncserver) :0 -localhost no -geometry 1280x800 -depth 24

      - name: Install Tailscale
        run: |
          brew install tailscale
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-macos-runner-${GITHUB_RUN_ID}
          TAILSCALE_IP=$(tailscale ip -4)
          echo "TAILSCALE_IP=$TAILSCALE_IP" >> "$GITHUB_ENV"

      - name: Verify VNC Service
        run: |
          if [ -d "/usr/local/bin" ]; then
            export PATH="/usr/local/bin:$PATH"
          elif [ -d "/opt/homebrew/bin" ]; then
            export PATH="/opt/homebrew/bin:$PATH"
          fi
          echo "VNC进程状态: $(ps aux | grep vncserver | grep -v grep)"
          nc -z -v "$TAILSCALE_IP" 5900 || echo "端口检查警告 - 尝试直接连接"

      - name: Keep Connection Alive
        run: |
          echo "=== VNC访问信息 ==="
          echo "地址: vnc://${TAILSCALE_IP}:5900"
          echo "用户名: runner"
          echo "密码: ${VNC_PASSWORD}"
          echo "桌面环境: Openbox"
          echo "==================="
          while true; do
            echo "[$(date)] VNC运行中 - 终止工作流以关闭"
            sleep 300
          done
