name: macOS VNC Server (Ultra Simple)

on:
  workflow_dispatch:

jobs:
  macos-vnc:
    runs-on: macos-latest
    timeout-minutes: 360

    steps:
      - name: 仅保留核心步骤（无换行）
        run: |
          # 1. 停止并配置VNC（一行命令，避免换行错误）
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -stop -agent && sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -allowAccessFor -allUsers -clientopts -setvnclegacy yes -setvncpw temp1234
          
          # 2. 生成随机密码
          VNC_PASS=$(openssl rand -hex 6)
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvncpw "$VNC_PASS"
          echo "VNC_PASSWORD=$VNC_PASS" >> $GITHUB_ENV
          echo "VNC_USER=runner" >> $GITHUB_ENV
          
          # 3. 提权并重启
          sudo dscl . -append /Groups/admin GroupMembership runner
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent

      - name: 启动Tailscale（简化版）
        run: |
          brew install tailscale
          sudo nohup /opt/homebrew/opt/tailscale/bin/tailscaled > /tmp/tailscaled.log 2>&1 &
          sleep 3
          sudo /opt/homebrew/bin/tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }}
          echo "TAILSCALE_IP=$(sudo /opt/homebrew/bin/tailscale ip -4)" >> $GITHUB_ENV

      - name: 访问信息
        run: |
          echo "地址: $TAILSCALE_IP:5900 | 用户名: runner | 密码: $VNC_PASSWORD"
          while true; do sleep 300; done
