name: macOS VNC Server

on:
  workflow_dispatch:

jobs:
  macos-vnc:
    runs-on: macos-latest
    timeout-minutes: 3600

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install RealVNC
        run: |
          brew install realvnc

      - name: Generate VNC password
        run: |
          PASS=$(tr -dc 'A-Za-z0-9!@#$%^&*' </dev/urandom | head -c 16)
          echo "$PASS" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          echo "VNC_PASSWORD=$PASS" >> "$GITHUB_ENV"

      - name: Configure RealVNC
        run: |
          mkdir -p ~/.vnc
          echo "geometry=1280x800" >> ~/.vnc/config
          echo "depth=24" >> ~/.vnc/config
          echo "localhost=no" >> ~/.vnc/config

      - name: Start VNC Server
        run: |
          vncserver :1

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Start tailscaled
        run: |
          sudo mkdir -p /var/run
          nohup sudo tailscaled >/tmp/tailscaled.log 2>&1 & disown
          sleep 3

      - name: Connect to Tailscale
        run: |
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-${GITHUB_RUN_ID}
          echo "TAILSCALE_IP=$(tailscale ip -4)" >> "$GITHUB_ENV"

      - name: Verify VNC Connection
        run: |
          echo "Tailscale IP: $TAILSCALE_IP"
          nc -z -v "$TAILSCALE_IP" 5901

      - name: Maintain Connection
        run: |
          echo "=== VNC ACCESS INFORMATION ==="
          echo "Address: ${TAILSCALE_IP}:5901"
          echo "Password: ${VNC_PASSWORD}"
          echo "Desktop: macOS"
          echo "=============================="
          while true; do
            echo "[$(date)] VNC Active - Cancel workflow to terminate"
            sleep 300
          done
