name: macOS VNC Server (TigerVNC)

on:
  workflow_dispatch:

jobs:
  macos-vnc:
    runs-on: macos-latest
    timeout-minutes: 3600

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install XQuartz (X11 Server) and TigerVNC
        run: |
          # 安装X11服务器（macOS运行图形界面必需）
          brew install --cask xquartz
          # 安装第三方VNC服务器（避免系统权限限制）
          brew install tigervnc

      - name: Configure VNC Server
        run: |
          export LC_ALL=C
          
          # 生成随机VNC密码
          VNC_PASS=$(openssl rand -hex 8)
          echo "VNC_PASSWORD=$VNC_PASS" >> "$GITHUB_ENV"
          
          # 初始化VNC配置
          mkdir -p ~/.vnc
          echo "$VNC_PASS" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          
          # 配置VNC启动脚本（启动X11和基本桌面环境）
          cat > ~/.vnc/xstartup << 'EOF'
          #!/bin/bash
          export DISPLAY=:0
          # 启动X11窗口管理器
          openbox &
          # 启动终端（可选）
          xterm &
          EOF
          chmod +x ~/.vnc/xstartup
          
          # 启动VNC服务器（绑定所有接口，分辨率1280x800）
          vncserver :0 -localhost no -geometry 1280x800 -depth 24

      - name: Install Tailscale
        run: |
          brew install tailscale
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-macos-runner-${GITHUB_RUN_ID}
          TAILSCALE_IP=$(tailscale ip -4)
          echo "TAILSCALE_IP=$TAILSCALE_IP" >> "$GITHUB_ENV"

      - name: Verify VNC Service
        run: |
          echo "Checking VNC port 5900..."
          lsof -i :5900 || echo "VNC server status check (may show nothing in CI)"
          nc -z -v "$TAILSCALE_IP" 5900 || echo "Port check warning (proceed to connect)"

      - name: Keep Connection Alive
        run: |
          echo "=== VNC ACCESS INFORMATION ==="
          echo "Address: vnc://${TAILSCALE_IP}:5900"
          echo "Username: runner"
          echo "Password: ${VNC_PASSWORD}"
          echo "Desktop: Openbox (轻量窗口管理器)"
          echo "=============================="
          while true; do
            echo "[$(date)] VNC Active - Terminate workflow to stop"
            sleep 300
          done
