name: macOS VNC Server

on:
  workflow_dispatch:

jobs:
  macos-vnc:
    runs-on: macos-latest
    timeout-minutes: 3600

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Remote Management
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -users $USER -privs -all -restart -agent -menu

      - name: Generate Random VNC Password
        run: |
          export VNC_PASSWORD=$(tr -dc 'A-Za-z0-9!@#$%^&*' </dev/urandom | head -c 16)
          echo "VNC_PASSWORD=${VNC_PASSWORD}" >> "$GITHUB_ENV"

      - name: Configure VNC Password
        env:
          VNC_PASSWORD: ${{ env.VNC_PASSWORD }}
        run: |
          sudo defaults write /Library/Preferences/com.apple.RemoteManagement.plist VNCPassword -string "${VNC_PASSWORD}"
          sudo launchctl kickstart -k system/com.apple.RemoteManagement

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Connect to Tailscale
        run: |
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-${GITHUB_RUN_ID}
          echo "TAILSCALE_IP=$(tailscale ip -4)" >> "$GITHUB_ENV"

      - name: Verify VNC Connection
        run: |
          nc -z -v "$TAILSCALE_IP" 5900

      - name: Maintain Connection
        run: |
          echo "=== VNC ACCESS INFORMATION ==="
          echo "Address: ${TAILSCALE_IP}:5900"
          echo "Password: ${VNC_PASSWORD}"
          echo "Desktop: macOS"
          echo "=============================="
          while true; do
            echo "[$(date)] VNC Active - Cancel workflow to terminate"
            sleep 300
          done
