name: macOS VNC Server (Final Fixed)

on:
  workflow_dispatch:

jobs:
  macos-vnc:
    runs-on: macos-latest
    timeout-minutes: 360

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 启用远程管理 + VNC 服务（关键修复）
        run: |
          # 完全启用远程管理，替代仅启用屏幕共享
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate \
            -configure -access -on \
            -configure -allowAccessFor -specifiedUsers \
            -configure -users runner \
            -privs -all \
            -restart -agent
          # 为 runner 用户设置独立 VNC 密码（不依赖系统用户密码）
          VNC_PASS=$(openssl rand -hex 6)
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -users runner \
            -setvncpw -vncpw "$VNC_PASS"
          echo "VNC_PASSWORD=$VNC_PASS" >> $GITHUB_ENV
          echo "VNC_USER=runner" >> $GITHUB_ENV

      - name: 安装并启动 Tailscale（确保服务正常）
        run: |
          brew install tailscale
          sudo nohup /opt/homebrew/opt/tailscale/bin/tailscaled > /tmp/tailscaled.log 2>&1 &
          sleep 3
          sudo /opt/homebrew/bin/tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=macos-vnc-final-${GITHUB_RUN_ID}
          echo "TAILSCALE_IP=$(sudo /opt/homebrew/bin/tailscale ip -4)" >> $GITHUB_ENV

      - name: 显示访问信息并保持会话
        run: |
          echo "=== 最终 VNC 访问信息 ==="
          echo "地址: $TAILSCALE_IP:5900"
          echo "用户名: $VNC_USER"
          echo "密码: $VNC_PASSWORD"
          echo "========================"
          
          while true; do
            echo "[$(date)] VNC 服务运行中..."
            sleep 300
          done
