name: macOS VNC Server

on:
  workflow_dispatch:

jobs:
  macos-vnc:
    runs-on: macos-latest
    timeout-minutes: 3600

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Random VNC Password
        run: |
          export VNC_PASSWORD=$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 8)
          echo "VNC_PASSWORD=${VNC_PASSWORD}" >> "$GITHUB_ENV"

      - name: Enable Remote Management and Set VNC Password
        env:
          VNC_PASSWORD: ${{ env.VNC_PASSWORD }}
        run: |
          osascript -e 'tell application "System Events" to set remote login to true'
          sudo defaults write /Library/Preferences/com.apple.RemoteManagement.plist VNCPassword -string "${VNC_PASSWORD}"
          killall SystemUIServer

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Connect to Tailscale
        run: |
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-${GITHUB_RUN_ID}
          echo "TAILSCALE_IP=$(tailscale ip -4)" >> "$GITHUB_ENV"

      - name: Verify VNC Connection
        run: |
          if nc -z -v "$TAILSCALE_IP" 5900; then
            echo "VNC connection verified!"
          else
            echo "VNC connection failed."
            exit 1
          fi

      - name: Maintain Connection
        run: |
          echo "=== VNC ACCESS INFORMATION ==="
          echo "Address: ${TAILSCALE_IP}:5900"
          echo "Password: ${VNC_PASSWORD}"
          echo "Desktop: macOS"
          echo "=============================="
          while true; do
            echo "[$(date)] VNC Active - Cancel workflow to terminate"
            sleep 300
          done
