name: macOS VNC Server (Simplified Fixed)

on:
  workflow_dispatch:

jobs:
  macos-vnc:
    runs-on: macos-latest
    timeout-minutes: 360

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 简化版配置VNC服务（无复杂格式转换）
        run: |
          # 1. 停止服务
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -stop -agent
          
          # 2. 直接用系统默认方式开启VNC（避免手动改plist）
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -allowAccessFor -allUsers \
            -setvncpw -vncpw "temp1234"  # 临时密码，后续会替换
            -setvnclegacy -vnclegacy yes  # 强制启用传统VNC认证（兼容客户端）
          
          # 3. 生成随机密码并直接生效
          VNC_PASS=$(openssl rand -hex 6)
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -setvncpw -vncpw "$VNC_PASS"
          echo "VNC_PASSWORD=$VNC_PASS" >> $GITHUB_ENV
          echo "VNC_USER=runner" >> $GITHUB_ENV
          
          # 4. 提升runner权限并重启服务
          sudo dscl . -append /Groups/admin GroupMembership runner
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent

      - name: 启动Tailscale
        run: |
          brew install tailscale
          sudo nohup /opt/homebrew/opt/tailscale/bin/tailscaled > /tmp/tailscaled.log 2>&1 &
          sleep 3
          sudo /opt/homebrew/bin/tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=macos-vnc-simple-${GITHUB_RUN_ID}
          echo "TAILSCALE_IP=$(sudo /opt/homebrew/bin/tailscale ip -4)" >> $GITHUB_ENV

      - name: 显示访问信息
        run: |
          echo "=== 访问信息 ==="
          echo "地址: $TAILSCALE_IP:5900"
          echo "用户名: $VNC_USER"
          echo "密码: $VNC_PASSWORD"
          echo "================="
          
          while true; do sleep 300; done
