name: macOS VNC Server (Fixed)

on:
  workflow_dispatch:

jobs:
  macos-vnc:
    runs-on: macos-latest
    timeout-minutes: 360

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable VNC (Screen Sharing)
        run: |
          # 强制启用屏幕共享服务（VNC）
          sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.screensharing.plist
          # 允许默认用户（runner）远程访问
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -users runner -access -on -privs -all

      - name: Generate VNC Password (No tr command)
        run: |
          # 用macOS原生支持的openssl生成密码（彻底避开tr的编码问题）
          VNC_PASS=$(openssl rand -hex 6)  # 生成12位十六进制密码（安全且无特殊字符）
          echo "VNC_PASSWORD=$VNC_PASS" >> $GITHUB_ENV

      - name: Set VNC Password for Default User
        run: |
          # 直接给默认用户runner设置VNC密码（无需创建新用户，无冲突）
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -users runner -setvncpw -vncpw "${{ env.VNC_PASSWORD }}"
          # 重启服务生效
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent

      - name: Install Tailscale
        run: |
          brew install tailscale
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=macos-vnc-fixed-${GITHUB_RUN_ID}
          echo "TAILSCALE_IP=$(tailscale ip -4)" >> $GITHUB_ENV

      - name: Keep Alive
        run: |
          echo "=== 访问信息 ==="
          echo "VNC地址: $TAILSCALE_IP:5900"
          echo "用户名: runner（系统默认用户，无需创建）"
          echo "密码: $VNC_PASSWORD"
          echo "================="
          
          while true; do
            echo "[$(date)] 运行中..."
            sleep 300
          done
