name: macOS VNC Server

on:
  workflow_dispatch:

jobs:
  macos-vnc:
    runs-on: macos-latest
    timeout-minutes: 3600

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Screen Sharing (VNC) with Fixed Configuration
        run: |
          # 强制字符编码为C，避免locale问题
          export LC_ALL=C
          
          # 关键修复：修正kickstart参数格式（苹果官方文档要求）
          # -allowAccessFor 后直接跟用户范围（无需连字符）
          # -privs 使用数字权限值（1073742079代表所有权限）
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate \
            -configure -access on \
            -configure -allowAccessFor allUsers \
            -configure -privs 1073742079 \
            -configure -restart -agent \
            -verbose  # 输出详细日志，便于排查错误
          
          # 生成随机密码（更稳定的方式）
          VNC_PASS=$(openssl rand -hex 8)  # 16位十六进制字符，避免特殊字符问题
          echo "VNC_PASSWORD=$VNC_PASS" >> "$GITHUB_ENV"
          
          # 设置VNC密码（修正参数传递方式）
          echo -n "$VNC_PASS" | sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -clientopts \
            -setvnclegacy yes \
            -setvncpw - \
            -verbose
          
          # 强制重启服务
          sudo launchctl stop com.apple.ARDAgent
          sudo launchctl start com.apple.ARDAgent

      - name: Install Tailscale
        run: |
          brew install tailscale
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-macos-runner-${GITHUB_RUN_ID}
          TAILSCALE_IP=$(tailscale ip -4)
          echo "TAILSCALE_IP=$TAILSCALE_IP" >> "$GITHUB_ENV"

      - name: Verify VNC Port
        run: |
          echo "Checking VNC port 5900 status..."
          netstat -an | grep 5900  # 检查端口是否监听
          nc -z -v "$TAILSCALE_IP" 5900 || echo "VNC port check failed (may be due to CI restrictions)"

      - name: Keep Connection Alive
        run: |
          echo "=== VNC ACCESS INFORMATION ==="
          echo "Address: vnc://${TAILSCALE_IP}:5900"
          echo "Username: runner"
          echo "Password: ${VNC_PASSWORD}"
          echo "=============================="
          while true; do
            echo "[$(date)] VNC Active - Terminate workflow to stop"
            sleep 300
          done
