name: macOS VNC + Tailscale (Working Version)

on:
  workflow_dispatch:

jobs:
  macos-vnc:
    runs-on: macos-latest
    timeout-minutes: 360

    steps:
      - name: 启用屏幕共享（VNC）
        run: |
          # 启用macOS内置屏幕共享（VNC服务）
          sudo defaults write /var/db/launchd.db/com.apple.launchd/overrides.plist com.apple.screensharing -dict Disabled -bool false
          sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.screensharing.plist
          # 为runner用户设置VNC密码
          VNC_PASS=$(openssl rand -hex 6)
          echo "password $VNC_PASS" | sudo tee ~/.vnc/passwd > /dev/null
          sudo chmod 600 ~/.vnc/passwd
          echo "VNC_PASSWORD=$VNC_PASS" >> $GITHUB_ENV
          echo "VNC_USER=runner" >> $GITHUB_ENV

      - name: 安装并启动Tailscale
        run: |
          brew install tailscale
          sudo nohup /opt/homebrew/opt/tailscale/bin/tailscaled > /tmp/tailscaled.log 2>&1 &
          sleep 3
          sudo /opt/homebrew/bin/tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=macos-vnc-working-${GITHUB_RUN_ID}
          echo "TAILSCALE_IP=$(sudo /opt/homebrew/bin/tailscale ip -4)" >> $GITHUB_ENV

      - name: 显示访问信息
        run: |
          echo "=== 最终访问信息 ==="
          echo "VNC地址: $TAILSCALE_IP:5900"
          echo "用户名: $VNC_USER"
          echo "密码: $VNC_PASSWORD"
          echo "===================="
          while true; do sleep 300; done
