name: Ubuntu VNC Server

on:
  workflow_dispatch:

jobs:
  ubuntu-vnc:
    runs-on: ubuntu-24.04
    timeout-minutes: 3600

    steps:
      - name: Update APT
        run: sudo apt-get update

      - name: Prevent service auto-start during apt
        run: |
          echo -e '#!/bin/sh\nexit 101' | sudo tee /usr/sbin/policy-rc.d >/dev/null
          sudo chmod +x /usr/sbin/policy-rc.d

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Disable systemctl hooks
        run: bash .github/workflows/scripts/disable-systemctl.sh

      - name: Pre-create system users and directories
        run: bash .github/workflows/scripts/precreate-users.sh

      - name: Install Desktop and VNC Server
        run: bash .github/workflows/scripts/install-desktop-vnc.sh

      - name: Validate system users and tmpfiles
        run: bash .github/workflows/scripts/validate-tmpfiles.sh

      - name: Re-enable service start
        run: bash .github/workflows/scripts/reenable-services.sh

      - name: Configure VNC Server
        run: |
          mkdir -p ~/.vnc
          PASS=$(tr -dc 'A-Za-z0-9!@#$%^&*' </dev/urandom | head -c 16)
          echo "$PASS" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          echo "VNC_PASSWORD=$PASS" >> "$GITHUB_ENV"
          cat > ~/.vnc/xstartup << 'EOF'
          #!/bin/bash
          unset SESSION_MANAGER
          unset DBUS_SESSION_BUS_ADDRESS
          [ -r "$HOME/.Xresources" ] && xrdb "$HOME/.Xresources"
          export XDG_SESSION_TYPE=x11
          export GDK_BACKEND=x11
          export QT_QPA_PLATFORM=xcb
          exec dbus-launch /usr/bin/gnome-session --session=gnome
          EOF
          chmod +x ~/.vnc/xstartup
          vncserver -kill :0 || true
          vncserver :0 -localhost no -geometry 1280x800 -depth 24 -xstartup ~/.vnc/xstartup

      - name: install shadowsocks
        run: bash .github/workflows/scripts/ubuntu-install-ss.sh

      - name: install frp
        run: bash .github/workflows/scripts/ubuntu-install-ss.sh
        
      - name: Restore systemctl hooks
        run: bash .github/workflows/scripts/restore-systemctl.sh

      - name: Keep Connection Alive
        run: |
          echo "=== PROXY ACCESS INFORMATION ==="
          echo "Address: 156.231.141.29:30000"
          echo "Password: Pass@Word1"
          echo "method: chacha20-ietf-poly1305"
          echo "=============================="
          while true; do
            echo "[$(date)] VNC Active - Cancel workflow to terminate"
            sleep 300
          done
